FROM node:14-alpine3.10 as builder
WORKDIR /usr/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4000
CMD node server.js

# docker build -t trentshailer/icc_database:<version num> .
# docker tag trentshailer/icc_database:<version num> trentshailer/icc_database:latest
# docker-compose up -d